### ISSUE TITLE
ELB listeners NOT updating

### ISSUE THREAD

**Issue by je-al** [docker/for-aws#70] opened 2017-07-20 22:59 UTC
(Hi, I'm actually evaluating the Docker Enterprise Edition (EE) for AWS (17031ee3 release) version, but since I'm not a customer (yet?) I'm doubtful about requesting support through the "commercial" channel...)

I've created a simple deployment consisting of 3 managers and 2 workers and issued:
`docker service create --name www --publish 80:80 nginx:1.11-alpine`

I can't access the service, and the External ELB is stuck with a single listener for port 7...

Looking around the containers, I've found one that's constantly restarting (`docker4x/l4controller-aws:17.03.1-ee-3-aws2`, which I'm assuming is the responsible for modifying the ELB), its logs go like this:

```
goroutine 1 [running]:
panic(0x835560, 0xc420302450)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.runCommand.func1.1(0xc4202be280)
        /go/src/github.com/docker/editions/aws/dockerfiles/elb-controller/files/cmd/run.go:95 +0xb4d
github.com/docker/editions/pkg/loadbalancer.ExposeServicePortInExternalLoadBalancer.func1(0xc4202be280, 0x1, 0x1)
        /go/src/github.com/docker/editions/pkg/loadbalancer/services.go:251 +0x12e
github.com/docker/editions/pkg/loadbalancer.(*poller).Run(0xc4201a3780, 0x7f101c4501b8, 0xc420014438, 0x0, 0x0)
        /go/src/github.com/docker/editions/pkg/loadbalancer/poll.go:186 +0x7ed
main.runCommand.func1(0xc4200c1400, 0xc42021f0c0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/editions/aws/dockerfiles/elb-controller/files/cmd/run.go:155 +0x90a
github.com/docker/editions/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200c1400, 0xc42021efa0, 0x2, 0x2, 0xc4200c1400, 0xc42021efa0)
        /go/src/github.com/docker/editions/vendor/github.com/spf13/cobra/command.go:561 +0x20c
github.com/docker/editions/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4200c1000, 0xc42015fee8, 0xc4200c1e00, 0xc420294000)
        /go/src/github.com/docker/editions/vendor/github.com/spf13/cobra/command.go:651 +0x367
github.com/docker/editions/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200c1000, 0xc42015fed8, 0x2)
        /go/src/github.com/docker/editions/vendor/github.com/spf13/cobra/command.go:610 +0x2b
main.main()
        /go/src/github.com/docker/editions/aws/dockerfiles/elb-controller/files/cmd/main.go:61 +0x411
time="2017-07-20T22:40:24Z" level=info msg="Connecting to docker: unix:///var/run/docker.sock"
time="2017-07-20T22:40:24Z" level=info msg="Not using TLS"
time="2017-07-20T22:40:24Z" level=info msg="Running on leader node: forceLeader= false"
time="2017-07-20T22:40:27Z" level=info msg="1 matches found. Processing."
panic: open /var/lib/docker/editions/elb.config: no such file or directory
```
Is this even the right place to be looking at?

I'm specially confounded by the fact that I've been creating a bunch of test deployments for a week now and this hadn't happened before (that I've noticed).

p.s.: I also have another issue, this one regarding the DTR, but don't know where to report it to, if you could be so kind as to point me to the right place... =P

**Comment by FrenchBen** [comment] 2017-07-20 23:53
@je-al Thanks for reporting this issue. 
Do you mind sharing the Mounts for that container?
You can easily get the output via something like:
```
docker inspect l4controller-aws -f '{{ range $s, $m := .Mounts }} Source: {{$m.Source}} -> Dest: {{$m.Destination}} | {{end}}'
```


_edit_
I did a quick analysis of the container and saw the issue. I pushed a patch out for it. Feel free to re-deploy and let us know if the issue is gone.

**Comment by kencochrane** [comment] 2017-07-21 12:30
@uday-shetty FYI

**Comment by je-al** [comment] 2017-07-21 13:19
@FrenchBen I had destroyed the stack by the time I saw your reply, and the one that I launched this morning (to see if the issue could be replicated) didn't have the problem. I do recall, however, that there was no volume associated with the path supposed to hold the `elb.config`, only connections to the docker socket and something else that escapes me right now...

**Comment by kencochrane** [comment] 2017-07-21 13:48
@je-al thanks for the update. @FrenchBen was able to push out a fix for your issue last night, so the new stack is most likely using the new code, and thus explains why you are not having any issues. 

I'm going to close this issue, but let us know if you need anything else.

**Closed as completed by kencochrane** 2017-07-21 13:48 UTC
