### ISSUE TITLE
Cloudstor do not resize EBS volume 

### ISSUE THREAD

**Issue by jippi** [docker/for-aws#149] opened 2018-04-09 09:04 UTC
### Expected behavior

```
$ docker run --rm -it --mount type=volume,volume-driver=cloudstor:aws,source=cw-test-vol,destination=/mydata,volume-opt=backing=relocatable,volume-opt=size=25,volume-opt=ebstype=gp2 ubuntu df -h /mydata/

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf        25G   45M   24G   1% /mydata

docker run --rm -it --mount type=volume,volume-driver=cloudstor:aws,source=cw-test-vol,destination=/mydata,volume-opt=backing=relocatable,volume-opt=size=30,volume-opt=ebstype=gp2 ubuntu df -h /mydata/

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf        30G   45M   29G   0% /mydata
```

### Actual behavior

```
$ docker run --rm -it --mount type=volume,volume-driver=cloudstor:aws,source=cw-test-vol,destination=/mydata,volume-opt=backing=relocatable,volume-opt=size=25,volume-opt=ebstype=gp2 ubuntu df -h /mydata/

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf        25G   45M   24G   1% /mydata

```
$ docker run --rm -it --mount type=volume,volume-driver=cloudstor:aws,source=cw-test-vol,destination=/mydata,volume-opt=backing=relocatable,volume-opt=size=30,volume-opt=ebstype=gp2 ubuntu df -h /mydata/

Filesystem      Size  Used Avail Use% Mounted on
/dev/xvdf        25G   45M   24G   1% /mydata
```

### Information

  - no errors in docker.log

**Comment by FrenchBen** [comment] 2018-04-09 18:51
That's expected - The EBS volume created isn't a resizable, as there are quite a few steps involved, that do not make sense to support at the plugin level (IMHO):
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modify-volume.html

It's much simpler to create a new one, at the desired size.

**Comment by djeeg** [comment] 2018-04-28 13:26
Trying to understand if online resizing of cloudstor EBS and EFS volumes is offically supported?
(dont really want to re-create/transfer data as that would likely cause an outage)

I couldnt see a full walk through of how to do this (however maybe have pieced together a plan from a number of links)

Resize the Elastic Volumes in AWS console
https://aws.amazon.com/blogs/aws/amazon-ebs-update-new-elastic-volumes-change-everything/

nsenter into the host
https://success.docker.com/article/how-can-i-gain-root-level-cli-access-to-a-docker-for-aws-azure-instance
`docker run --rm -it --privileged --pid=host debian nsenter -t 1 -m -u -n -i sh`

Then resize the file system
https://success.docker.com/article/can-cloudstor-volumes-be-resized
```
df -h | grep ebs
df -h | grep efs
resize2fs /dev/xvdh
```

This test seems to work, wondering if is offically supported?

**Comment by jippi** [comment] 2018-04-28 15:45
having Cloudstor resize the EBS volume, and letting the `resize2fs` (or similar) be up the operator should be a feature, imo :)

**Comment by FrenchBen** [comment] 2018-04-30 17:49
As of right now, it's not officially supported. Perhaps future implementations will have this feature added.
Closing, as the issue is resolved. It would be good to have a new issue opened with a `Feature proposal` title attached to it, with the above. @djeeg or @jippi would you mind doing that?
The more information/use-case would be helpful, so that we can gauge interest.

**Closed as completed by FrenchBen** 2018-04-30 17:49 UTC
Labels: status/0-wont-fix

**Comment by djeeg** [comment] 2018-04-30 17:55
@FrenchBen, okay auto-resize triggered/driven by the Cloudstor plugin is not currently supported.

However is manual resize using AWS API+tools (eg resize2fs ) supported? (that would mean that the cloudstor size configs would be out-of-sync with what was actually on the EBS) Or is that unsupported as well?

**Comment by FrenchBen** [comment] 2018-04-30 18:03
@djeeg "unofficially" this should work. 
We only check the argument size during initial creation. If we have to move AZ, then we rely on the snapshot size to create the new volume.
