### ISSUE TITLE
Is this abandoned? All traces are gone from docs.docker.com

### ISSUE THREAD

**Issue by mrmachine** [docker/for-aws#163] opened 2018-07-19 04:06 UTC
I can't find any announcement about Docker for AWS EOL?

**Comment by gary-cowell** [comment] 2018-07-19 08:38
Getting worried that this has gone right after the release of 18.06

Edit: the docker docs github has lots of commits explicitly removing the for-aws and for-azure documentation, e.g.

https://github.com/docker/docker.github.io/commit/1b082617861b197f3c31c257395f355f39585c5c

**Comment by beingamarnath** [comment] 2018-07-19 09:11
I came over to create the issue that no docs were found on docker for aws and the issue is already created. Lets hope its some kind of error, otherwise we are in deep trouble..

**Comment by talolard** [comment] 2018-07-19 12:43
Oh my

**Comment by ambrons** [comment] 2018-07-19 12:56
I opened this documentation defect, but a few others seem to have done it as well
https://github.com/docker/docker.github.io/issues/7051

What concerns me more is that it would appear that no docker employees have responded to any issues on this repo in a few months.  I was originally thinking it had to do with DockerCon, but that's over and I still don't see any replies.  My assumption was the days of "free support" were over and perhaps this repo is going to become defunct.

No documentation seems to suggest otherwise.  I'm hoping my tin-foil-hat is wrong here.

**Comment by hairyhenderson** [comment] 2018-07-19 20:20
FYI: https://github.com/docker/docker.github.io/commit/14e01eea810cd3cff08a4f202f982a955d6a312c

Looks like the change has been reverted... _The plot thickens..._

**Comment by gary-cowell** [comment] 2018-07-19 20:28
It's very curious because the excision seemed surgical. Hard to believe it was an error. Silence is deafening.

**Comment by mrmachine** [comment] 2018-07-19 21:45
My guess is they want docker for AWS to be EE only.

**Comment by brawong** [comment] 2018-07-19 22:40
Hi Folks - apologies... unfortunately while updating the docs to prep for the new Docker CE release channels, these were removed. They should have been added back now.

**Comment by mrmachine** [comment] 2018-07-19 22:43
Only to be removed again next week. No doubt this was just someone jumping the gun.

**Comment by brawong** [comment] 2018-07-19 22:56
Actually, D4AWS-EE has been deprecated (https://store.docker.com/editions/enterprise/docker-ee-aws) for Docker Certified Infrastructure, but D4AWS-CE is still available (https://store.docker.com/editions/community/docker-ce-aws)

**Comment by brawong** [comment] 2018-07-19 23:45
Closing as this has been fixed.

**Closed as completed by brawong** 2018-07-19 23:45 UTC
