### ISSUE TITLE
Services using cloudstor volume plugin may have issues across upgrades when D4AWS version changes

### ISSUE THREAD

**Issue by hairyhenderson** [docker/for-aws#11] opened 2017-02-23 04:57 UTC
_Note: I haven't actually run into any issues with this yet, mostly because I _just_ started experimenting with cloudstor in 17.03.0-beta19. @mavenugo asked me to log this, however_ 😁

### Expected behavior

Volumes persisted by cloudstor should continue to be available across D4AWS upgrades.

### Actual behavior

When upgrading D4AWS, the version of cloudstor will also change, leading to a version mismatch. This will mean a service won't be able to access its volumes, because the volume driver's tag will have changed.

### Information

The CFN template should probably make use of `--alias` when installing the plugin. This command:

```
docker plugin install --grant-all-permissions docker4x/cloudstor:$DOCKER_FOR_IAAS_VERSION CLOUD_PLATFORM=AWS EFS_ID_REGULAR=$EFS_ID_REGULAR EFS_ID_MAXIO=$EFS_ID_MAXIO DEBUG=1
```

should probably change to something like:

```
docker plugin install --alias cloudstor --grant-all-permissions docker4x/cloudstor:$DOCKER_FOR_IAAS_VERSION CLOUD_PLATFORM=AWS EFS_ID_REGULAR=$EFS_ID_REGULAR EFS_ID_MAXIO=$EFS_ID_MAXIO DEBUG=1
```

### Steps to reproduce the behavior

  1. Create a service that uses cloudstor:
```console
$ docker service create --replicas 5 --name ping1 \
    --mount type=volume,volume-driver=docker4x/cloudstor:aws-v1.13.1-beta18,source=sharedvol1,destination=/shareddata \
    alpine ping docker.com
```
  2. Upgrade D4AWS and watch the service fail because the volume driver has been updated to `docker4x/cloudstor:aws-v17.03.0-ce-rc1-beta19`

**Comment by mavenugo** [comment] 2017-02-23 05:01
Thanks @hairyhenderson. Yes, `--alias` seems to be the better solution.
But we have to confirm if the service plugin filter also considers `alias` properly when used with the `--mount` options.

**Comment by mavenugo** [comment] 2017-02-23 05:21
I confirmed that using plugin `--alias` works as expected. We will fix that appropriately in the next beta release.

**Comment by kencochrane** [comment] 2017-02-23 13:25
Thanks @mavenugo and @hairyhenderson

**Comment by nathanleclaire** [comment] 2017-03-07 22:33
FYI @ddebroy -- just in case you hadn't seen this already

**Comment by kencochrane** [comment] 2017-03-29 18:37
This should be in the next edge release.

**Comment by kencochrane** [comment] 2017-04-07 15:52
This is in the latest edge release. closing this issue

**Closed by kencochrane** 2017-04-07 15:52 UTC
Labels: status/3-fixed, status/4-fix-released-beta

**Comment by hairyhenderson** [comment] 2017-04-07 18:47
huzzah! thanks @kencochrane!
