### ISSUE TITLE
Sporadic container dropouts

### ISSUE THREAD

**Issue by goloroden** [docker/for-aws#10] opened 2017-02-22 19:43 UTC
This one is hard to reproduce, but I have experienced it for several weeks now.

I am running Docker for AWS on 5 servers, 3 managers (t2.micro) and 2 workers (t2.medium). I use this setup to run a bunch of containers (~10) that contain web servers. Basically, everything works fine.

Sometimes (but it is only *sometimes*) if I stop and restart a container, or if I update a container to a newer image, I then experience dropouts of some of the containers. The dropouts do not necessarily affect the one that was restarted / updated, it's more like random. This usually results in HTTP requests that are not answered, or that are answered, but extremely slow.

What's strange is that this does not happen on all containers, only on some of them. But, it's not always the same ones. AWS CloudWatch doesn't show any problems. All server instances are up and running, the load balancer works as expected.

I have double-checked the available memory, there is more than 50% free memory. Also, the CPUs don't have lots to do, and there are so much CPU balance credits left (as said, *t* instances) that it can hardly be the reason for the dropouts.

This usually lasts for a few hours, then everything becomes normal again. Sometimes, it takes longer, and what helps then, is most of the times (but again, not always) to stop and start the problematic containers once more. It is better to do this sequentially with 30 seconds between them, than to do it at once.

I can pretty sure say that it is not AWS, and that it is not the applications within the containers (because, as long as you don't touch them, and if they are running perfectly, they keep running perfectly). To me it looks as if there was an internal hickup in the Docker mesh, or something like that …

Any ideas?

**Comment by goloroden** [comment] 2017-02-23 07:03
PPS: Now, half a day later, everything is back to normal. A few hours ago it suddenly started to "just work" again. I did not change *anything*. It just happened. And I highly guess (from my experience from the past weeks) that now things keep to run perfectly, until I update one of the containers again…

**Comment by goloroden** [comment] 2017-02-23 08:07
PPS: Having searched the web, I found https://github.com/docker/docker/issues/25325 … this looks pretty much like the effects I experience on AWS.

**Comment by goloroden** [comment] 2017-02-23 12:05
I have found out that when I try to start the containers, I often get this error message, even multiple times in a row:

> starting container failed: address already in use

Sometimes, Swarm then decides to start both instances (the websites are configured to run with 2 replicas) on the same server.

**Comment by kencochrane** [comment] 2017-02-23 13:22
@goloroden that's for the report, can you let us know which version of docker for AWS you are using?

I'm wondering if your initial issue is a clock sync issue, but not sure until I can try and reproduce.

**Comment by goloroden** [comment] 2017-02-23 15:05
According to the CloudFormation template it's:

> Docker for AWS 1.13.0 (1)

**Comment by kencochrane** [comment] 2017-02-23 15:40
OK, I'm not sure but maybe it is a bug in 1.13.0 that might have been fixed in 1.13.1? But I'm not 100% sure. Just another possibility. 

FYI we have a new stable docker for AWS version available for docker 1.13.1 see https://docs.docker.com/docker-for-aws/release-notes/ for more details.

You should be able to upgrade from one version to the other with no downtime, if you are willing to give it a try. https://docs.docker.com/docker-for-aws/upgrade/

**Comment by goloroden** [comment] 2017-02-23 15:47
I'll give it a try… as soon as the update has finished, I'll report back.

**Comment by kencochrane** [comment] 2017-02-23 15:53
@goloroden thanks, I'm not sure it will fix your issue, but since there were known bugs that were fixed in 1.13.1 it is probably a good place to be anyway. If you still see the issue, please let us know, so we can get to the bottom of it.

**Comment by goloroden** [comment] 2017-02-23 16:40
The update has passed, and I am still able to SSH connect into the managers.

But when I try to run any Docker command, e.g. to show the status of the services, I get this error:

> Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

What shall I do?

**Comment by kencochrane** [comment] 2017-02-23 18:05
hmm, This is looking look a clock skew issue we have seen on AWS in the past. Let me find out a little more, and get back to you shortly. I need to confirm from someone else who had the clock skew issue that they saw this error as well.

**Comment by kencochrane** [comment] 2017-02-23 18:14
@goloroden if you haven't done it already can you run `docker-diagnose`?  https://docs.docker.com/docker-for-aws/faqs/#/where-do-i-report-problems-or-bugs

**Comment by goloroden** [comment] 2017-02-23 18:19
First of all: Thanks you so very much for taking the time to look into my issues, that's really great 😊 

I didn't know about `docker-diagnose` before, but I have now run it, and this is its output:

> OK hostname=ip-172-31-16-50-eu-central-1-compute-internal session=1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> OK hostname=ip-172-31-31-232-eu-central-1-compute-internal session=1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> OK hostname=ip-172-31-13-228-eu-central-1-compute-internal session=1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> OK hostname=ip-172-31-15-63-eu-central-1-compute-internal session=1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> OK hostname=ip-172-31-29-156-eu-central-1-compute-internal session=1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> Done requesting diagnostics.
> Your diagnostics session ID is 1487873884-xPtlDDy3jv9rq4DZxaUXBX2WkXxQllJq
> Please provide this session ID to the maintainer debugging your issue.

**Comment by kencochrane** [comment] 2017-02-24 00:34
Thank you for sending that over. I haven't had a chance to review all of the data yet, but I'll try and get to it shortly and see if there is anything I can find wrong with your setup. Are you still having issues with the error:

> "Error response from daemon: rpc error: code = 4 desc = context deadline exceeded"

**Comment by goloroden** [comment] 2017-02-24 05:26
Yes, I still get the error message.

**Comment by goloroden** [comment] 2017-02-24 20:12
Just in case this is important, I *still* do get the same error message.

**Comment by kencochrane** [comment] 2017-02-24 20:50
@goloroden sorry for the delay, I have been busy with something else. I haven't had a chance to look at the data yet. A few more questions.

Do you get the same error from all manager nodes? Or is this just one manager that is causing the issue?

**Comment by goloroden** [comment] 2017-02-24 23:10
No problem 😊

I have checked this, and I get the same error regardless of the manager I SSH into.

**Comment by kencochrane** [comment] 2017-02-25 00:12
@goloroden oh that stinks. so it does it for every docker command, even docker info and docker version?

**Comment by goloroden** [comment] 2017-02-25 08:57
Interesting question - and interesting results ;-)

I have tried to run the following commands:

- ✅ `docker ps`: Works
- ✅ `docker version`: Works
- ⚠️ `docker info`: Works, but pretty slow (~20s)
- ⚠️ `docker service ls`: Does not work (error as above, takes ~20s)

The results are the same, no matter which manager I connect to.

Additionally, because you mentioned clock skew, I have compared the time on all three managers manually, and it's the same everywhere.

**Comment by kencochrane** [comment] 2017-02-25 16:11
@goloroden ok, once again sorry for the slowness. I finally got around to looking at your diagnostic output and it looks like you lost your swarm for some reason. We have two options at this point.

1. We start all over with a new stack. This is easiest but you will lose anything running on the current cloudformation stack.

2. We try and recover the stack.

For 1. All you need to do is create a new docker for AWS stack using the latest CFN template, and then when happy delete the broken one.

For 2. We need to login to the servers and run some commands to try and recover the nodes. Here is roughly what we need to do.

### Managers

1. We will login to one of the manager nodes, `ip-172-31-15-63-eu-central-1-compute-internal` looks like a good one. that one says it isn't in a swarm, so we can run 

```
export PRIVATE_IP=`wget -qO- http://169.254.169.254/latest/meta-data/local-ipv4`
echo "Private IP = $PRIVATE_IP"
docker swarm init --listen-addr $PRIVATE_IP:2377 --advertise-addr $PRIVATE_IP:2377
```

that will initialize a new swarm. Wait 5 minutes to make sure docker for aws notices this is the new leader and updates the dynamodb table with the new leaders IP address (you can confirm this worked by looking in the aws console, and view the docker for aws dynamodb table to confirm the value is the private IP address for this manager) 

At this point we have two options, we can either restart one of the other managers (via aws EC2 console) and let it come up and rejoin automatically, which is cleanest, but loses anything on that node, or we can manually join the swarm. Important to note, since this is in an autoscaling group, it most likely won't start the same instance, it will shut down that instance and replace with another one.

If you do the restart method, you need to restart each manager one at a time, and check docker node ls on the primary manager to make sure it joined correctly. Once the second one has joined, you can do the same for the last one. 

To manually join the swarm you will run `docker swarm join-token manager` on the primary manager from step 1 above. This will get you the command and token to run on the other managers in the swarm. So SSH into those other managers and run the commands.

If you run `docker node ls` on the primary you should see the 3 managers now.

### Workers
Once again for the workers, you have two options you can restart them one at a time via the AWS EC2 console, and see if they join the swarm correctly, or you can SSH to them and run the join worker command with the token and manually join them.

To get the worker command and token, run `docker swarm join-token worker` from the primary manager, and then ssh into the workers and run the command.

SSH access to the workers nodes is blocked from the public internet so you will need to first ssh into a manager, and then ssh over to the worker over the private network. See https://docs.docker.com/docker-for-aws/deploy/#/connecting-via-ssh for more notes on how to connect to the workers, you can get the private Ips from the AWS EC2 dashboard for those instances.

### more info

I know that is a lot to take in, but basically what we are trying to do is reconnect each instance into a swarm, and since something went wrong (not sure what) we need to do it by hand.

If you have any other questions, please let me know.

Sorry for the slow response.

**Comment by goloroden** [comment] 2017-02-25 16:23
Hmmmm … first of all, thanks for your detailed reply.
Unfortunately, I already hang at step 1 😞

You wrote:

> We will login to one of the manager nodes, `ip-172-31-15-63-eu-central-1-compute-internal` looks like a good one.

AFAICS this is one of the workers, so I wasn't sure what to do. Since you explicitly talked about managers in this group, I tried one of the managers (private IP = `172.31.13.228`), and ran the following commands there:

```bash
$ export PRIVATE_IP=`wget -qO- http://169.254.169.254/latest/meta-data/local-ipv4`
$ echo "Private IP = $PRIVATE_IP"
$ docker swarm init --listen-addr $PRIVATE_IP:2377 --advertise-addr $PRIVATE_IP:2377
```

This printed the private IP address as expected, but the last command failed:

> Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.

Now I'm completely confused … you said that the nodes didn't form a swarm, but they say they do?

Am I missing something?

**Comment by kencochrane** [comment] 2017-02-25 16:30
@goloroden sorry, it was hard for me to tell which nodes where the workers and which ones were the managers, the one I picked looked like a manager, but I could have been wrong. You will need a manager, so feel free to pick one you know is a manager.

It is possible the swarm leader who they are trying to connect too is no longer around, and thus they think they are in a swarm, but in reality there is no swarm for them to belong too.

If you run a `docker info` and look at the swarm output what does it say?

My guess is that we will still need to restart the swarm from scratch, which will mean leaving the swarm it thinks it is in, so we can restart the swarm from scratch with the swarm init command.

**Comment by goloroden** [comment] 2017-02-25 17:09
I just ran `docker info`, and the output is pretty interesting:

```bash
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: v4yr2oafsiwumussesaa9mojv
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 ClusterID: 
 Managers: 0
 Nodes: 0
 Orchestration:
  Task History Retention Limit: 0
 Raft:
  Snapshot Interval: 0
  Heartbeat Tick: 0
  Election Tick: 0
 Dispatcher:
  Heartbeat Period: Less than a second
 CA Configuration:
  Expiry Duration: Less than a second
 Node Address: 172.31.13.228
 Manager Addresses:
  172.31.10.2:2377
  172.31.13.116:2377
  172.31.13.228:2377
  172.31.16.50:2377
  172.31.29.68:2377
  172.31.31.232:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991 MiB
Name: ip-172-31-13-228.eu-central-1.compute.internal
ID: 42ZL:WGVI:FZWR:7E2M:B2E4:QBUY:ZIE3:JFEO:QIQY:U2B5:ANPW:WMLT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 69
 Goroutines: 135
 System Time: 2017-02-25T17:03:12.46966679Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Obviously it knows about the swarm, it knows that there are 5 running containers, that the swarm is active (at least it thinks so), and so on ...

What makes me wonder is these lines:

```
Manager Addresses:
  172.31.10.2:2377
  172.31.13.116:2377
  172.31.13.228:2377
  172.31.16.50:2377
  172.31.29.68:2377
  172.31.31.232:2377
```

This list contains the private IP addresses of all the current managers, but what are those other three addresses?

**Comment by kencochrane** [comment] 2017-02-25 17:18
Those are probably the manager IP addresses for the managers that you had before you upgraded. For some reason they were never removed from the swarm. Probably another reason why it is messed up, the swarm has lost quorum. 

Another reason why we will need to reset the swarm. 

Do you get any results from `docker node ls` On the same node you ran docker info?

**Comment by goloroden** [comment] 2017-02-25 17:25
No, unfortunately this results in the well-known

> Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

message 😢 

Is it possible to just remove those IP addresses, instead of having to rebuild the swarm from scratch? Because, as it seems, the swarm is still there, it just contains too many managers.

Since 50% of them do not exist any more, maybe this is the reason for the `contect deadline exceeded` message? (I'm not a Go developer, but from my understanding this has something to do with a timeout, hasn't it?)

**Comment by kencochrane** [comment] 2017-02-25 17:32
You can try and demote and remove those nodes, but I don't think it will work since you are getting an error when running docker node ls. Feel free to try and see what happens, worse case it will give you the same error.

**Comment by goloroden** [comment] 2017-02-25 17:34
As you expected, things didn't work out, same error as before.

So just that I get things right: This now means that I have to leave the swarm on every manager (because they still think that they are part of a swarm), and then rebuild a new swarm, right?

**Comment by kencochrane** [comment] 2017-02-25 17:46
Yes, that is correct. Pick one manager as the new primary manager and one at a time leave the other swarm and join the new one.

**Comment by goloroden** [comment] 2017-02-25 17:58
Okay, somehow I messed it up 😞

I'm very sorry, because I would have loved to figure this out. Anyway, I now deleted the stack and am going to set it up using Cloud Formation again. Basically, this then brings us back to the initial issue of flaky containers when updating them …

Let's see if this still happens with the new Docker for AWS version.

**Comment by kencochrane** [comment] 2017-02-25 18:07
Hmm, sorry for your issues, if it happens again please let us know. We would love to find the cause, so it doesn't happen again.

**Comment by goloroden** [comment] 2017-02-25 18:09
Absolutely no problem, and no need to excuse 😉 

As said before, I'm very thankful for your help!
If it happens again, I'll let you know.

Until then, shall we close this issue, or would you like to keep it open for a while?

**Comment by kencochrane** [comment] 2017-02-25 19:03
I'll close the issue and we can reopen if it happens again.

**Closed by kencochrane** 2017-02-25 19:03 UTC
