### ISSUE TITLE
one node unable to use the routing mesh

### ISSUE THREAD

**Issue by hutchic** [docker/for-aws#38] opened 2017-05-01 15:44 UTC
### Expected behavior
started docker for aws with three manager nodes and 5 worker nodes. Launched a service and published the port. Should be able to request the service through the IP:PORT of every worker and manager node

### Actual behavior
One node is unable to route the request

### Information

```
~ $ docker-diagnose 
OK hostname=ip-172-31-25-93-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-37-182-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-14-0-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-28-43-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-26-222-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-5-159-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-2-91-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
OK hostname=ip-172-31-42-22-ec2-internal session=1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
Done requesting diagnostics.
Your diagnostics session ID is 1493652718-R3sgDMv3uA4uGzGeFI8G9aFk5YSnp8bb
Please provide this session ID to the maintainer debugging your issue.
```

### Steps to reproduce the behavior

  1. start docker-for-aws
  2. start a service with a published port
  3. ```curl `curl -s http://169.254.169.254/latest/meta-data/local-ipv4/\`:9024/instances/all/ | xargs -I ? bash -c "curl ?:10003/version"```

https://gist.github.com/hutchic/5207c306984cd1ccd3565e2fd684c17e#file-gistfile1-txt-L12

Ran the `docker-diagnose` and the `curl` from the instance that is derp'd. I suspect either the EC2 instance is slightly wrong or a docker service responsible for the routing mesh on this particular instance is having issues. Regardless it should mark itself as unhealthy and let the ASG cycle it IMO

**Comment by kencochrane** [comment] 2017-05-04 18:41
@hutchic are you still seeing this error?

Just so I make sure I understand what is going on. You deployed a service, and you can connect to it from all of the hosts except 1?

- Which host are you having a hard time connecting too (a worker, a manager)?  
- Are you trying to connect from one host to another, or trying to connect to the service on the same host?
- did you try connecting from another host to see if it was just a connection from that one host.

**Comment by hutchic** [comment] 2017-05-05 04:53
The routing mesh for any service with a published port fails should you request that port on a specific instance - ie the routing mesh on this one instance seems derp'd

The gist is requesting a published port via the private IP's of every instance that's part of the swarm. You can see there's one that fails. The instance in question is a manager instance.

End result is a very challenging to track 502 (or 504 I don't recall).

**Comment by kencochrane** [comment] 2017-05-08 19:08
Sorry if I'm repeating myself, just trying to make sure we are on the same page.

- In your example, which node did you run the code in the gist from? Was it a different node then the one that had the error (172.31.37.182)?
- did you try connecting from another host to see if you have the same results?

**Comment by hutchic** [comment] 2017-05-10 20:40
> In your example, which node did you run the code in the gist from? Was it a different node then the one that had the error (172.31.37.182)?

Yes a different node

> connecting from another host to see if you have the same results?

Same result from other hosts

**Comment by RehanSaeed** [comment] 2018-02-12 13:45
Just had this happen to one of my nodes that I've now replaced to fix the problem.

**Comment by FrenchBen** [comment] 2018-02-12 18:52
Since the issue is close to a year old, closing to let new details added within a new issue.

Thanks @RehanSaeed for searching :)

**Closed by FrenchBen** 2018-02-12 18:52 UTC

**Comment by hutchic** [comment] 2018-02-13 17:14
@FrenchBen I'm fine with this being closed (don't have this problem with a newer version of docker swarm) but the reasoning for closing it because of missing details feels incorrect. If more information was required I was never asked to provide it.
